"""Webbläsartest av adminpanelens funktioner: texter, ångra/historik, sök, klickbar karta, menyn,
jobb, statistik, lediga uppdrag, schemaläggning, kopiering, bildbank och styrelseskifte.

Kräver en nollställd lokal databas:  npm run preview:node -- --reset
"""
import re
import time
import urllib.request

from common import BASE, OUT, check, done, login, plain, test_image, sync_playwright


def get(path: str, ua: str = "Mozilla/5.0 (Macintosh) Test") -> tuple[int, str, dict]:
    class NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *a, **k):  # noqa: D401
            return None

    opener = urllib.request.build_opener(NoRedirect)
    req = urllib.request.Request(BASE + path, headers={"User-Agent": ua})
    try:
        with opener.open(req) as r:
            return r.status, r.read().decode("utf-8", "replace"), {k.lower(): v for k, v in r.headers.items()}
    except urllib.error.HTTPError as e:  # 3xx/4xx
        return e.code, e.read().decode("utf-8", "replace"), {k.lower(): v for k, v in e.headers.items()}


with sync_playwright() as p:
    browser = p.chromium.launch()
    ctx = browser.new_context(viewport={"width": 1440, "height": 900}, locale="sv-SE")
    page = ctx.new_page()
    errors: list[str] = []
    page.on("console", lambda m: errors.append(m.text) if m.type == "error" else None)
    page.on("pageerror", lambda e: errors.append(str(e)))

    print("Inloggning")
    login(page)
    check("/admin" in page.url, "inloggad i adminpanelen")

    # ───────── Översikt: klickbar webbplats ─────────
    print("Översikt och klickbar karta")
    page.goto(f"{BASE}/admin")
    frame_el = page.locator("[data-map-frame]")
    check(frame_el.count() == 1, "kartan över webbplatsen finns på Översikt")
    page.wait_for_function("() => { const f = document.querySelector('[data-map-frame]'); return f && f.contentDocument && f.contentDocument.body && f.contentDocument.body.getAttribute('data-map-ready') }", timeout=15000)
    frame = page.frame_locator("[data-map-frame]")
    marked = frame.locator("[data-eu]").count()
    check(marked > 40, f"många klickbara delar på startsidan ({marked})")
    frame.locator("#hero-titel").hover()
    time.sleep(0.2)
    label = frame.locator(".em-label").inner_text()
    check("Startsidan" in label and "Rubrik" in label, f"etiketten visar var texten ändras ({label!r})")
    page.screenshot(path=str(OUT / "oversikt.png"))
    frame.locator("#hero-titel").click()
    page.wait_for_url(re.compile(r"/admin/texter\?sida=startsida&falt=hero_title"))
    check(True, "klick på rubriken leder till rätt fält")
    page.wait_for_timeout(600)
    focused = page.evaluate("document.activeElement && document.activeElement.name")
    check(focused == "hero_title", f"fältet får fokus ({focused})")

    # Klick på ett event i kartan → eventets redigeringssida
    page.goto(f"{BASE}/admin")
    page.wait_for_function("() => document.querySelector('[data-map-frame]').contentDocument.body.getAttribute('data-map-ready')", timeout=15000)
    ev = page.frame_locator("[data-map-frame]").locator(".event-card").first
    if ev.count():
        ev.click()
        page.wait_for_url(re.compile(r"/admin/event/\d+$"))
        check(True, "klick på ett event leder till eventets sida i panelen")
    # Klick på menyn i kartan → menyredigeraren
    page.goto(f"{BASE}/admin")
    page.wait_for_function("() => document.querySelector('[data-map-frame]').contentDocument.body.getAttribute('data-map-ready')", timeout=15000)
    page.frame_locator("[data-map-frame]").locator(".nav-link").first.click()
    page.wait_for_url(re.compile(r"sida=meny"))
    check(True, "klick på menyn leder till menyredigeraren")

    # ───────── Texter: redigera, förhandsvisa, spara, ångra, historik ─────────
    print("Texter och sidor")
    page.goto(f"{BASE}/admin/texter")
    check(page.locator(".page-card").count() >= 19, "alla sidor visas som kort")
    page.screenshot(path=str(OUT / "texter-oversikt.png"))
    page.goto(f"{BASE}/admin/texter?sida=startsida")
    open_sections = page.locator("details[data-section][open]").count()
    check(open_sections == 1, "ett avsnitt är öppet från början")
    page.locator("details[data-section] > summary").nth(2).click()
    page.wait_for_timeout(200)
    check(page.locator("details[data-section][open]").count() == 1, "bara ett avsnitt öppet åt gången")
    page.locator("details[data-section] > summary").first.click()
    more = page.locator("details[data-section][open] .more-texts > summary").first
    if more.count():
        more.click()
        check(page.locator("details[data-section][open] .more-texts[open]").count() == 1, "”Visa fler texter” öppnar de extra fälten")
    page.fill("textarea[name=hero_title], input[name=hero_title]", "En helt ny rubrik för testet")
    page.wait_for_function("() => { const f = document.querySelector('[data-lp-frame]'); const h = f && f.contentDocument && f.contentDocument.querySelector('#hero-titel'); return h && h.textContent.includes('En helt ny rubrik') }", timeout=10000)
    check(True, "förhandsvisningen visar den nya rubriken innan den sparas")
    reset = page.locator('[data-reset="hero_title"]')
    check(reset.is_visible(), "”Återställ originaltexten” syns när texten ändrats")
    # Klick i förhandsvisningen hoppar till fältet
    page.frame_locator("[data-lp-frame]").locator("[data-ek=intro_title]").click()
    page.wait_for_timeout(700)
    check(page.evaluate("document.activeElement && document.activeElement.name") == "intro_title", "klick på en text i förhandsvisningen öppnar fältet")
    page.screenshot(path=str(OUT / "texter-startsida.png"))
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart=texter&andring="))
    check(page.locator(".undo-box").count() == 1, "kvitto med Ångra-knapp efter sparning")
    status, body, _ = get("/")
    check("En helt ny rubrik för testet" in plain(body), "ny rubrik syns på webbplatsen")
    page.click(".undo-box button[type=submit]")
    page.wait_for_url(re.compile(r"klart=angrat"))
    status, body, _ = get("/")
    check("En helt ny rubrik för testet" not in plain(body), "Ångra återställer rubriken")
    page.goto(f"{BASE}/admin/texter/historik?nyckel=hero_title")
    versions = page.locator(".version-item").count()
    check(versions >= 4, f"historiken visar versionerna ({versions} rader)")
    # Återställ den nya rubriken via historiken (bekräftelsedialogen godkänns)
    page.once("dialog", lambda d: d.accept())
    page.locator(".version-item:has-text('En helt ny rubrik') form button").first.click()
    page.wait_for_url(re.compile(r"klart=aterstallt-text"))
    status, body, _ = get("/")
    check("En helt ny rubrik för testet" in plain(body), "en tidigare version kan återställas")
    page.screenshot(path=str(OUT / "historik.png"))
    # Tillbaka till originalet
    page.once("dialog", lambda d: d.accept())
    page.locator(".version-original form button").click()
    page.wait_for_url(re.compile(r"klart=aterstallt-text"))
    status, body, _ = get("/")
    check("En helt ny rubrik för testet" not in body, "originaltexten kan återställas")

    # Obligatoriskt fält tomt → fel
    page.goto(f"{BASE}/admin/texter?sida=startsida")
    page.fill("[name=hero_title]", "")
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_load_state()
    check(page.locator(".alert-error").count() == 1 and page.locator("details[data-section][open] .has-error").count() >= 1, "tomt obligatoriskt fält ger ett tydligt fel i rätt avsnitt")

    # Gemensamt: knapptext ändras överallt
    page.goto(f"{BASE}/admin/texter?sida=gemensamt&falt=join_label")
    page.fill("[name=join_label]", "Gå med i JFK")
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart=texter"))
    status, body, _ = get("/om-oss")
    check(body.count("Gå med i JFK") >= 2, "”Bli medlem”-knapparna får den nya texten")

    # Om oss: utseendet på toppen och utskotten väljs i adminpanelen
    for key, value, css in [("about_hero_style", "delad", "page-top--delad"), ("committees_style", "karusell", "committees--karusell")]:
        page.goto(f"{BASE}/admin/texter?sida=om-oss&falt={key}")
        page.locator(f"label:has(input[name={key}][value={value}])").click()
        page.click("#texter-form .sticky-actions button[type=submit]")
        page.wait_for_url(re.compile(r"klart=texter"))
        status, body, _ = get("/om-oss")
        check(css in body, f"utseendet {value} syns på Om oss")
    # Undersidornas topp: utan bild visas bara text, med bild det valda utseendet
    page.goto(f"{BASE}/admin/texter?sida=bli-medlem&falt=member_hero_style")
    page.locator("label:has(input[name=member_hero_style][value=delad])").click()
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart=texter"))
    status, body, _ = get("/bli-medlem")
    check("page-top--delad" not in body and 'class="page-hero"' in body, "utan bilder visas bara texten även om ett bildutseende är valt")
    page.goto(f"{BASE}/admin/texter?sida=bli-medlem&falt=member_image_1")
    page.locator("input[type=file][name=member_image_1]").set_input_files(str(OUT / "texter-oversikt.png"))
    page.wait_for_timeout(1200)
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart=texter"), timeout=60000)
    status, body, _ = get("/bli-medlem")
    check("page-top--delad" in body and "collage-fallback-pattern" in body, "med en bild visas valt utseende, med mönsterrutor där bilder saknas")
    page.goto(f"{BASE}/admin/texter?sida=gemensamt&falt=page_hero_default")
    page.locator("label:has(input[name=page_hero_default][value=bildband])").click()
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart=texter"))
    page.goto(f"{BASE}/admin/texter?sida=bli-medlem&falt=member_hero_style")
    page.locator("label:has(input[name=member_hero_style][value=standard])").click()
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart=texter"))
    status, body, _ = get("/bli-medlem")
    check("page-top--bildband" in body, "”Som de andra sidorna” följer valet under Gemensamt")

    page.goto(f"{BASE}/om-oss")
    page.locator(".committees--karusell .committee-grid").focus()
    check(page.evaluate("document.activeElement.classList.contains('committee-grid')"), "karusellen kan nås med tangentbordet")
    for key, value in [("about_hero_style", "kollage"), ("committees_style", "mork")]:
        page.goto(f"{BASE}/admin/texter?sida=om-oss&falt={key}")
        page.locator(f"label:has(input[name={key}][value={value}])").click()
        page.click("#texter-form .sticky-actions button[type=submit]")
        page.wait_for_url(re.compile(r"klart=texter"))

    # ───────── Sidans uppbyggnad ─────────
    print("Sidans uppbyggnad")
    page.goto(f"{BASE}/admin/texter?sida=startsida")
    check(page.locator(".sec-group").count() == 8, "startsidans avsnitt kan flyttas (handtag på åtta avsnitt)")
    page.locator('.sec-group[data-block="instagram"] [data-drag-handle]').focus()
    for _ in range(7):
        page.keyboard.press("ArrowUp")
    check(page.input_value("[data-block-order]").startswith("instagram,"), "piltangenterna flyttar avsnittet")
    g = page.locator('.sec-group[data-block="varden"]')
    g.locator("summary").first.click()
    g.locator("[data-block-visible]").uncheck()
    page.locator("#avsnitt-toppen > summary").click()
    st = page.locator('[data-text-style="hero_title"]')
    st.locator("summary").click()
    st.locator("[data-style-size]").fill("140")
    st.locator('label:has(input[value=center])').click()
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart="))
    status, body, _ = get("/")
    order = re.findall(r'<section class="[^"]*" aria-labelledby="([a-z-]+)"', body)
    check(order[:2] == ["hero-titel", "insta-titel"] and "varden-titel" not in order, f"ordningen och dolda avsnitt syns på webbplatsen ({order[:3]})")
    check('[data-t="hero_title"]{zoom:1.4;text-align:center!important' in body and 'data-t="hero_title"' in body, "rubrikens storlek och justering används")
    page.goto(f"{BASE}/admin/texter?sida=startsida")
    page.evaluate("document.querySelector('[data-block-order]').value = 'partners,varden,intro,evenemang,nyheter,paverka,instagram'")
    g = page.locator('.sec-group[data-block="varden"]')
    g.locator("summary").first.click()
    g.locator("[data-block-visible]").check()
    page.locator("#avsnitt-toppen > summary").click()
    page.locator('[data-text-style="hero_title"] [data-style-reset]').click()
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart="))
    status, body, _ = get("/")
    check('data-t="hero_title"' not in body and "varden-titel" in body, "allt kan återställas")

    # Senast ändrad
    page.goto(f"{BASE}/admin/texter?sida=startsida")
    lc = page.locator(".last-change")
    check(lc.count() == 1 and "Senast ändrad av dig i dag" in lc.inner_text(), f"sidan visar vem som senast ändrade den ({lc.inner_text() if lc.count() else '–'})")
    page.goto(f"{BASE}/admin/texter")
    check("Senast ändrad av dig" in page.locator(".page-card:has-text('Startsidan')").inner_text(), "översikten visar senaste ändringen per sida")
    check(page.locator(".page-card:has-text('Dokument') .page-card-changed").count() == 0, "orörda sidor visar ingen ändring")

    # Återställ sidans uppbyggnad med en knapp
    page.goto(f"{BASE}/admin/texter?sida=om-oss")
    check(page.locator(".layout-reset").count() == 0, "ingen återställningsruta när uppbyggnaden är orörd")
    page.locator('.sec-group[data-block="samarbeten"] [data-drag-handle]').focus()
    page.keyboard.press("ArrowUp")
    g = page.locator('.sec-group[data-block="pedagog"]')
    g.locator("summary").first.click()
    g.locator("[data-block-visible]").uncheck()
    page.click("#texter-form button[type=submit]:has-text('Spara')")
    page.wait_for_url(re.compile(r"klart="))
    box = page.locator(".layout-reset")
    check(box.count() == 1 and "Ny ordning och 1 dolt avsnitt" in box.inner_text(), "rutan sammanfattar vad som är ändrat")
    page.screenshot(path=str(OUT / "aterstall-uppbyggnad.png"))
    page.once("dialog", lambda d: d.accept())
    box.locator("button").click()
    page.wait_for_url(re.compile(r"klart=uppbyggnad_aterstalld"))
    status, body, _ = get("/om-oss")
    order = re.findall(r'<section class="[^"]*" aria-labelledby="([a-z-]+)"', body)
    check(order[-2:] == ["arets-pedagog", "samarbeten"] and page.locator(".layout-reset").count() == 0, "knappen återställer ordningen och visar alla avsnitt igen")

    # Dölj en hel sida
    page.goto(f"{BASE}/admin/texter?sida=kontakt")
    page.locator("label.switch").click()
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart="))
    status, body, _ = get("/kontakt")
    check(status == 404, "en dold sida svarar ”Sidan finns inte”")
    status, body, _ = get("/")
    check('href="/kontakt"' not in body, "länkarna till en dold sida försvinner ur menyn och sidfoten")
    status, body, _ = get("/sitemap.xml")
    check("/kontakt<" not in body, "en dold sida finns inte i sitemap.xml")
    page.goto(f"{BASE}/admin/texter")
    check(page.locator(".page-card:has-text('Kontakt') .badge-hidden").count() == 1, "översikten visar att sidan är dold")
    page.goto(f"{BASE}/admin/texter?sida=kontakt")
    page.locator("label.switch").click()
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart="))
    status, _, _ = get("/kontakt")
    check(status == 200, "sidan kan visas igen")

    # ───────── Instagram ─────────
    print("Instagram")
    status, body, _ = get("/")
    check("insta-empty" in body, "utan inlägg visas en vänlig text och Följ-knappen")
    page.goto(f"{BASE}/admin/instagram")
    check(page.locator("details.insta-sync").count() == 1, "rutan förklarar hur automatisk hämtning slås på")
    for i, cap in enumerate(["Vårbanketten 2026", "Lunchföreläsning med Vinge", "Innebandyturneringen"]):
        page.goto(f"{BASE}/admin/instagram/ny")
        page.locator("input[type=file][name=image_key]").set_input_files(str(test_image(OUT / f"insta{i}.jpg", (1080, 1080), (40 + i * 60, 90, 140))))
        page.fill("[name=caption]", cap)
        page.fill("[name=posted_at]", f"2026-09-2{i}")
        page.fill("[name=permalink]", f"https://www.instagram.com/p/test{i}/")
        page.wait_for_timeout(600)
        page.click("form.admin-form button[type=submit]")
        page.wait_for_url(re.compile(r"/admin/instagram\?"))
    status, body, _ = get("/")
    check(body.count('<li class="insta-post">') == 3 and "insta--karusell" in body and "data-marquee" in body, "inläggen visas i ett rullande band på startsidan")
    check(body.count('<li class="insta-post" aria-hidden="true">') >= 5 and 'tabindex="-1"' in body, "upprepningarna i bandet är dolda för skärmläsare och tangentbord")
    check("data-marquee-toggle" in body, "det rullande bandet har en paus-knapp")
    check(body.index("Innebandyturneringen") < body.index("Vårbanketten 2026"), "det senaste inlägget visas först")
    check('href="https://www.instagram.com/p/test0/"' in body and 'rel="noopener"' in body, "inläggen länkar till Instagram i ny flik")
    page.goto(f"{BASE}/admin/texter?sida=startsida&falt=insta_style")
    page.locator("label:has(input[name=insta_style][value=rutnat])").click()
    page.locator("label:has(input[name=insta_background][value=mork])").click()
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart="))
    status, body, _ = get("/")
    check("insta--rutnat" in body and "insta-bg-mork" in body and "data-marquee" not in body and "data-carousel" not in body, "utseende och bakgrund kan bytas")
    page.goto(f"{BASE}/admin/texter?sida=startsida&falt=insta_style")
    page.locator("label:has(input[name=insta_style][value=karusell])").click()
    page.locator("label:has(input[name=insta_background][value=ljus])").click()
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart="))

    # ───────── JFK Idrott ─────────
    print("JFK Idrott")
    status, body, _ = get("/for-studenter")
    check("sport--band" in body and "data-marquee" not in body and "feature-grid" in body, "utan bilder visas aktiviteterna utan rörelse")
    page.goto(f"{BASE}/admin/texter?sida=for-studenter&falt=sport_image")
    for i, k in enumerate(["sport_image", "sport_image_2", "sport_image_3"]):
        page.locator(f"input[type=file][name={k}]").set_input_files(str(test_image(OUT / f"idrott{i}.jpg", (1200, 900), (30 + i * 70, 120, 90))))
    page.wait_for_timeout(1500)
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart="), timeout=60000)
    status, body, _ = get("/for-studenter")
    check("marquee-photos" in body and body.count('<li class="marquee-item">') == 3 and 'aria-hidden="true"' in body and "data-motion-toggle" in body, "med bilder rullar de i ett band med paus-knapp")
    for style, marker in [("bildspel", "fader-hero"), ("delad", "fader-split"), ("kort", "marquee-cards")]:
        page.goto(f"{BASE}/admin/texter?sida=for-studenter&falt=sport_style")
        page.locator(f"label:has(input[name=sport_style][value={style}])").click()
        page.click("#texter-form .sticky-actions button[type=submit]")
        page.wait_for_url(re.compile(r"klart="))
        status, body, _ = get("/for-studenter")
        check(marker in body, f"utseendet {style} visas")
    page.goto(f"{BASE}/for-studenter")
    page.mouse.move(5, 5)
    page.wait_for_timeout(300)
    page.goto(f"{BASE}/admin/texter?sida=for-studenter&falt=sport_style")
    page.locator("label:has(input[name=sport_style][value=band])").click()
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart="))

    # ───────── Utskott (klickbara kort på Engagera dig) ─────────
    print("Utskott")
    status, body, _ = get("/engagera-dig")
    check(body.count('data-cm') >= 6 and 'id="utskott-arbetsmarknadsutskottet"' in body, "den gamla utskottslistan har flyttats över till egna kort")
    page.goto(f"{BASE}/admin/utskott")
    check(page.locator(".admin-table tbody tr").count() >= 6, "utskotten finns under Styrelse och uppdrag → Utskott")
    page.goto(f"{BASE}/admin/utskott/ny")
    page.fill("[name=name]", "Testutskottet")
    page.fill("[name=summary]", "Ett utskott för testerna.")
    page.fill("[name=body]", "Här gör vi **viktiga** saker.\n\n- Möten\n- Fika")
    page.fill("[name=commitment]", "En timme i veckan")
    page.locator("input[type=file][name=image_1_key]").set_input_files(str(test_image(OUT / "utskott1.jpg", (1200, 800), (50, 90, 160))))
    page.fill("[name=image_1_alt]", "Testbild")
    page.wait_for_timeout(800)
    page.click("form.admin-form button[type=submit]")
    page.wait_for_url(re.compile(r"/admin/utskott\?klart="))
    page.goto(f"{BASE}/engagera-dig")
    card = page.locator("#utskott-testutskottet")
    check(card.count() == 1 and not card.get_attribute("open"), "det nya utskottet visas som ett stängt kort")
    card.locator("summary").click()
    page.wait_for_timeout(400)
    check(card.get_attribute("open") is not None and card.locator(".cm-body .prose strong").inner_text() == "viktiga" and card.locator(".cm-photo img").count() == 1, "ett klick fäller ut kortet med beskrivning och bild")
    page.locator("#utskott-arbetsmarknadsutskottet summary").click()
    page.wait_for_timeout(400)
    check(page.locator("[data-cm][open]").count() == 1, "bara ett kort är utfällt åt gången")
    page.goto(f"{BASE}/engagera-dig#utskott-testutskottet")
    page.wait_for_timeout(400)
    check(page.locator("#utskott-testutskottet[open]").count() == 1, "en länk till #utskott-namn öppnar rätt kort")
    page.locator("#utskott-testutskottet .cm-text a.btn").click()
    page.wait_for_load_state()
    check(page.locator("[name=uppdrag]").input_value() == "Testutskottet", "knappen förväljer utskottet i intresseformuläret")
    status, body, _ = get("/om-oss")
    check('href="/engagera-dig#utskott-testutskottet"' in body, "korten på Om oss länkar till utskottet på Engagera dig")

    # ───────── Anmälan stängd / öppnar automatiskt ─────────
    print("Anmälan stängd")
    def set_signup(status: str, opens: str, closes: str = "") -> None:
        page.goto(f"{BASE}/admin/texter?sida=engagera-dig&falt=engage_signup")
        page.locator(f"label:has(input[name=engage_signup][value={status}])").click()
        page.fill("[name=engage_signup_opens]", opens)
        page.fill("[name=engage_signup_closes]", closes)
        page.click("#texter-form .sticky-actions button[type=submit]")
        page.wait_for_url(re.compile(r"klart="))
    set_signup("stangd", "")
    status, body, _ = get("/engagera-dig")
    check("signup-closed" in body and 'data-form="engagemang"' not in body and "Ansökan öppnar TBA" in body, "stängd anmälan utan datum visar rutan med TBA i stället för formuläret")
    check("Anmälan öppnar TBA" in body, "utskottens knapp säger att anmälan är stängd")
    page.goto(f"{BASE}/engagera-dig")
    before = page.request.post(f"{BASE}/engagera-dig", form={"namn": "Stängd Test", "epost": "stangd@example.se", "uppdrag": "Idrottsutskottet"})
    page.goto(f"{BASE}/admin/meddelanden")
    check("Stängd Test" not in page.content(), "inskick tas inte emot medan anmälan är stängd")
    set_signup("stangd", "2099-03-01T12:00")
    status, body, _ = get("/engagera-dig")
    check("Ansökan öppnar 1 mars 2099 kl. 12.00" in body, "med ett datum visas datumet")
    check("sc-band-svart" in body and "data-countdown-reload" in body, "standard är svart banderoll med nedräkning")
    # Egna färger: färgväljaren fyller i hexkoden, "Standard" tömmer den, ogiltig färg ger fel
    page.goto(f"{BASE}/admin/texter?sida=engagera-dig&falt=engage_closed_c_bg")
    page.locator("[data-color-pick]:has(#falt-engage_closed_c_bg) input[type=color]").evaluate("e => { e.value = '#14365c'; e.dispatchEvent(new Event('input', { bubbles: true })); }")
    check(page.input_value("#falt-engage_closed_c_bg") == "#14365c", "färgväljaren fyller i hexkoden")
    # Ingen automatik: panelen frågar om rubrik, text och länkar ska anpassas efter den nya bakgrunden
    ask = page.locator(".color-ask")
    check(ask.count() == 1 and "blir vit" in ask.inner_text(), "panelen frågar om de andra färgerna ska anpassas")
    ask.locator("button", has_text="Ja, anpassa").click()
    check(page.input_value("#falt-engage_closed_c_text") == "#ffffff" and page.locator(".color-ask").count() == 0, "”Ja, anpassa” fyller i de föreslagna färgerna")
    check(page.locator("[data-color-pick]:has(#falt-engage_closed_c_bg) + .color-swatches .color-swatch").count() >= 3, "sajtens färger finns som snabbval")
    page.fill("#falt-engage_closed_c_accent", "#abcdef")
    page.locator("[data-color-pick]:has(#falt-engage_closed_c_accent) [data-color-clear]").click()
    check(page.input_value("#falt-engage_closed_c_accent") == "", "knappen Standard tömmer färgen")
    page.fill("#falt-engage_closed_c_title", "blå")
    page.click("#texter-form .sticky-actions button[type=submit]")
    check(page.locator("#falt-engage_closed_c_title[aria-invalid=true]").count() == 1, "ogiltig färg ger ett felmeddelande")
    page.fill("#falt-engage_closed_c_title", "")
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart="))
    status, body, _ = get("/engagera-dig")
    check("--sc-bg:#14365c;" in body and "sc-c-bg" in body and "--sc-text:#ffffff;" in body and "--sc-title" not in body, "de valda färgerna används – och ingenting fylls i automatiskt")
    page.goto(f"{BASE}/admin/texter?sida=engagera-dig&falt=engage_closed_countdown")
    page.locator("label:has(input[name=engage_closed_countdown][value=av])").click()
    page.fill("#falt-engage_closed_c_bg", "")
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart="))
    status, body, _ = get("/engagera-dig")
    check("data-countdown" not in body and "sc-c-bg" not in body, "nedräkningen kan stängas av och färgen återställas")
    page.goto(f"{BASE}/admin/texter?sida=engagera-dig&falt=engage_closed_countdown")
    page.locator("label:has(input[name=engage_closed_countdown][value=pa])").click()
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart="))
    for style, marker in [("gul", "signup-closed--gul"), ("nedrakning", "data-countdown"), ("diskret", "open-badge")]:
        page.goto(f"{BASE}/admin/texter?sida=engagera-dig&falt=engage_closed_style")
        page.locator(f"label:has(input[name=engage_closed_style][value={style}])").click()
        page.click("#texter-form .sticky-actions button[type=submit]")
        page.wait_for_url(re.compile(r"klart="))
        status, body, _ = get("/engagera-dig")
        check(marker in body, f"utseendet {style} för stängd anmälan visas")
    set_signup("stangd", "2020-01-01T08:00")
    status, body, _ = get("/engagera-dig")
    check('data-form="engagemang"' in body and "signup-closed" not in body, "anmälan öppnar automatiskt när datumet har passerat")
    set_signup("oppen", "", "2099-05-01T18:00")
    status, body, _ = get("/engagera-dig")
    check('data-form="engagemang"' in body and "signup-deadline" in body and "Anmälan stänger 1 maj 2099 kl. 18.00" in body and "data-countdown-reload" not in body, "öppen anmälan visar nedräkning till när den stänger")
    set_signup("oppen", "", "2020-01-01T08:00")
    status, body, _ = get("/engagera-dig")
    check("signup-closed" in body and 'data-form="engagemang"' not in body, "anmälan stänger automatiskt när tiden har passerat")
    set_signup("stangd", "2020-01-01T08:00", "2099-05-01T18:00")
    status, body, _ = get("/engagera-dig")
    check('data-form="engagemang"' in body and "signup-deadline" in body, "öppnar- och stänger-tid tillsammans ger ett anmälningsfönster")
    set_signup("oppen", "")

    # ───────── Gamla adresser (styrelsens egna omdirigeringar) ─────────
    print("Gamla adresser")
    page.goto(f"{BASE}/admin/texter?sida=felsidor&falt=redirects")
    page.fill("[name=redirects]", "/om-jfk/styrelsen.html → /kontakt\nhttps://jfkarlstad.se/gammal-kampanj -> /bli-medlem")
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart="))
    r = page.request.get(BASE + "/om-jfk/styrelsen.html", max_redirects=0)
    check(r.status == 301 and r.headers.get("location") == "/kontakt", "styrelsens egen omdirigering går före den inbyggda")
    r = page.request.get(BASE + "/gammal-kampanj", max_redirects=0)
    check(r.status == 301 and r.headers.get("location") == "/bli-medlem", "egen omdirigering för en adress utan filändelse")
    page.goto(f"{BASE}/admin/texter?sida=felsidor&falt=redirects")
    page.fill("[name=redirects]", "/a.html → https://exempel.se/")
    page.click("#texter-form .sticky-actions button[type=submit]")
    check(page.locator("#falt-redirects[aria-invalid=true]").count() == 1, "omdirigering till en annan webbplats stoppas med ett felmeddelande")
    page.fill("[name=redirects]", "")
    page.click("#texter-form .sticky-actions button[type=submit]")
    page.wait_for_url(re.compile(r"klart="))

    # ───────── Sök ─────────
    print("Sök")
    page.goto(f"{BASE}/admin")
    page.fill("#topp-sok", "Gå med i JFK")
    page.press("#topp-sok", "Enter")
    page.wait_for_url(re.compile(r"/admin/sok\?q="))
    hit = page.locator(".admin-hit").first
    check(hit.count() == 1 and "join_label" in (hit.get_attribute("href") or ""), "sök hittar texten och länkar till fältet")
    page.goto(f"{BASE}/admin/sok?q=inspark")
    check(page.locator(".search-group-admin").count() >= 1, "sök hittar innehåll (event/nyheter)")
    page.screenshot(path=str(OUT / "admin-sok.png"))
    status, body, _ = get("/sok?q=inspark")
    check("search-hit" in body and "<mark>" in body.lower(), "sök på webbplatsen visar markerade träffar")
    status, body, _ = get("/sok?q=%3Cscript%3Ealert(1)%3C%2Fscript%3E")
    check("<script>alert(1)" not in body, "sökordet escapas på webbplatsen")

    # ───────── Menyn ─────────
    print("Menyn")
    page.goto(f"{BASE}/admin/texter?sida=meny")
    page.fill("#meny-paverka", "Påverka")
    row = page.locator("[data-menu-item]:has(#meny-kontakt) > [data-menu-row] [data-move=up]")
    row.click()
    page.locator("[data-menu-row]:has(#meny-aktuellt) [data-menu-visible]").uncheck()
    page.wait_for_timeout(800)
    page.screenshot(path=str(OUT / "menyn.png"))
    page.click("#meny-form button[type=submit]:not([name])")
    page.wait_for_url(re.compile(r"klart=meny"))
    status, body, _ = get("/")
    nav = re.search(r'<ul class="nav-list">(.*?)</ul>\s*<div class="nav-mobile-cta">', body, re.S)
    nav_html = nav.group(1) if nav else ""
    check(">Påverka<" in nav_html, "nytt menynamn syns")
    check('href="/aktuellt"' not in re.sub(r'<ul class="sub-menu".*?</ul>', "", nav_html, flags=re.S), "dold menypunkt syns inte")
    check(nav_html.find('href="/kontakt"') < nav_html.find('href="/jf-paverka"'), "ny ordning syns")
    page.once("dialog", lambda d: d.accept())
    page.click("#meny-form button[name=aterstall]")
    page.wait_for_url(re.compile(r"sida=meny"))
    status, body, _ = get("/")
    check(">JF Påverka<" in body and 'href="/aktuellt"' in body, "standardmenyn kan återställas")

    # ───────── Bildbank och uppladdning ─────────
    print("Bildbank")
    img = test_image(OUT / "test.jpg")
    page.goto(f"{BASE}/admin/nyheter/ny")
    page.fill("[name=title]", "Testnyhet med bild")
    page.fill("[name=body]", "Brödtext.")
    page.set_input_files("#falt-image_key", str(img))
    page.wait_for_function("() => { const i = document.querySelector('[data-small-for=image_key]'); return i && i.files && i.files.length === 1 }", timeout=10000)
    check(True, "en liten version skapas i webbläsaren")
    page.click("form.admin-form button[type=submit]")
    page.wait_for_url(re.compile(r"/admin/nyheter\?klart="))
    page.goto(f"{BASE}/admin/bildbank")
    cards = page.locator(".media-card").count()
    check(cards >= 1, f"bilden finns i bildbanken ({cards})")
    src = page.locator(".media-card img").first.get_attribute("src") or ""
    s_status, _, s_headers = get(src)
    check(src.endswith(".sm") and s_status == 200 and "image/" in s_headers.get("content-type", ""), "den lilla versionen serveras")
    check("Nyhet: Testnyhet med bild" in page.content(), "bildbanken visar var bilden används")
    page.screenshot(path=str(OUT / "bildbank.png"))
    # Välj bilden från bildbanken i en annan nyhet
    page.goto(f"{BASE}/admin/nyheter/ny")
    page.fill("[name=title]", "Andra nyheten")
    page.click("[data-bank-open=image_key]")
    page.wait_for_selector(".bank-pick")
    page.screenshot(path=str(OUT / "bildbank-valj.png"))
    page.locator(".bank-pick").first.click()
    check(page.locator("[data-bank-for=image_key]").input_value() != "", "vald bild från bildbanken fylls i")
    page.click("form.admin-form button[type=submit]")
    page.wait_for_url(re.compile(r"/admin/nyheter\?klart="))
    page.goto(f"{BASE}/admin/bildbank")
    check("Andra nyheten" in page.content(), "samma bild används nu på två ställen")
    # Justera bildens passform: fokuspunkt och zoom gäller överallt där bilden används
    page.locator(".media-adjust").first.click()
    page.wait_for_url(re.compile(r"/admin/bildbank/justera\?nyckel="))
    fit_key = page.url.split("nyckel=")[1].split("&")[0]
    page.click(".fit-numbers > summary")
    page.fill("[data-fit-x]", "20")
    page.fill("[data-fit-y]", "80")
    page.locator("[data-fit-zoom]").fill("1.5")
    page.click("button[type=submit]:has-text('Spara')")
    page.wait_for_url(re.compile(r"klart=justerat"))
    status, body, _ = get("/aktuellt")
    check(f'img[data-img="{fit_key}"]{{object-fit:cover!important;object-position:20% 80%' in body and "scale(1.5)" in body, "justerad bild får fokuspunkt och zoom på webbplatsen")
    page.goto(f"{BASE}/admin/bildbank/justera?nyckel={fit_key}")
    page.click("button[name=aterstall]")
    page.wait_for_url(re.compile(r"klart=aterstallt_bild"))
    status, body, _ = get("/aktuellt")
    check(f'img[data-img="{fit_key}"]{{' not in body, "”Återställ till original” tar bort justeringen")
    page.goto(f"{BASE}/admin/bildbank/justera?nyckel=..%2F..%2Fetc")
    check("/admin/bildbank" in page.url and "justera" not in page.url, "ogiltig bildnyckel leder tillbaka till bildbanken")

    # Ladda upp en bild direkt i bildbanken och ta bort den (används inte)
    page.set_input_files("#falt-bild", str(test_image(OUT / "test2.jpg", (900, 600), (200, 60, 60))))
    page.wait_for_timeout(500)
    page.click(".bank-upload-form button[type=submit]")
    page.wait_for_url(re.compile(r"/admin/bildbank\?klart=skapat"))
    page.goto(f"{BASE}/admin/bildbank?visa=oanvanda")
    unused = page.locator(".media-card").count()
    check(unused == 1, "filtret ”Används inte” visar den oanvända bilden")
    page.once("dialog", lambda d: d.accept())
    page.locator(".media-card form button").first.click()
    page.wait_for_url(re.compile(r"klart=raderat"))
    check(page.locator(".media-card").count() == 0, "en oanvänd bild kan tas bort")

    # ───────── Jobb och praktik + statistik ─────────
    print("Jobb och statistik")
    page.goto(f"{BASE}/admin/jobb/ny")
    page.fill("[name=title]", "Sommarnotarie 2027")
    page.select_option("[name=employer_pick]", index=1)
    check(not page.locator("[name=employer]").is_visible(), "namnfältet döljs när arbetsgivaren väljs i listan")
    page.select_option("[name=kind]", "sommarnotarie")
    page.fill("[name=location]", "Stockholm")
    page.fill("[name=summary]", "Arbeta som notarie under sommaren.")
    page.fill("[name=body]", "## Om tjänsten\n\nDu får arbeta med riktiga ärenden.")
    page.fill("[name=apply_url]", "https://example.com/ansok")
    page.fill("[name=deadline]", "2030-01-31")
    page.click("form.admin-form button[type=submit]")
    page.wait_for_url(re.compile(r"/admin/jobb\?klart="))
    status, body, _ = get("/karriar")
    check("Sommarnotarie 2027" in body, "tjänsten syns på /karriar")
    slug = re.search(r'href="/karriar/([^"?]+)"', body)
    status, body, _ = get(f"/karriar/{slug.group(1)}") if slug else (0, "", {})
    check(status == 200 and "JobPosting" in body, "tjänstens sida har JobPosting-data")
    job_id = re.search(r'href="/ut/ansok/(\d+)"', body)
    st, _, hdr = get(f"/ut/ansok/{job_id.group(1)}") if job_id else (0, "", {})
    check(st == 302 and hdr.get("location") == "https://example.com/ansok", "/ut/ansok leder vidare till ansökan")
    st, _, _ = get("/ut/ansok/99999")
    check(st == 404, "okänd utlänk ger 404 (ingen öppen omdirigering)")
    get("/karriar/" + slug.group(1), ua="Googlebot/2.1") if slug else None
    status, body, _ = get("/")
    check("count-pill" in body, "startsidan visar antal lediga tjänster")
    page.goto(f"{BASE}/admin/partners/statistik")
    content = page.content()
    check("Statistik till partners" in content and page.locator(".stats-table").count() >= 1, "statistiksidan visar tabellen")
    check(page.locator(".stats-table").nth(1).locator("td.num").first.inner_text().strip() == "1", "en visning av annonsen räknas (roboten räknas inte)")
    page.screenshot(path=str(OUT / "statistik.png"), full_page=True)
    st, csv, hdr = get("/admin/partners/statistik.csv")  # utan inloggning
    check(st in (302, 303), "statistiken kräver inloggning")

    # Arbetsgivare som inte är partners: snabbval, logotyp på annonsen och egen statistik
    page.goto(f"{BASE}/admin/arbetsgivare/ny")
    page.fill("[name=name]", "Förvaltningsrätten i Karlstad")
    page.locator("input[type=file][name=logo_key]").set_input_files(str(test_image(OUT / "arbetsgivare.jpg", (600, 200), (20, 60, 120))))
    page.wait_for_timeout(1500)
    page.click("form.admin-form button[type=submit]")
    page.wait_for_url(re.compile(r"/admin/arbetsgivare\?klart="))
    check("Förvaltningsrätten i Karlstad" in page.content(), "arbetsgivaren syns i listan")
    page.locator("a", has_text="+ Lägg upp en tjänst").first.click()
    page.wait_for_load_state()
    check(page.locator("[name=employer_pick] option:checked").inner_text() == "Förvaltningsrätten i Karlstad", "”Lägg upp en tjänst” förväljer arbetsgivaren")
    page.fill("[name=title]", "Notarie vid förvaltningsrätten")
    page.fill("[name=apply_url]", "https://example.com/notarie")
    page.click("form.admin-form button[type=submit]")
    page.wait_for_url(re.compile(r"/admin/jobb\?klart="))
    status, body, _ = get("/karriar")
    m = re.search(r'href="/karriar/(notarie-vid-forvaltningsratten[^"?]*)"', body)
    check(bool(m) and "Förvaltningsrätten i Karlstad" in body, "annonsen syns med arbetsgivarens namn")
    status, jbody, _ = get(f"/karriar/{m.group(1)}") if m else (0, "", {})
    check('class="job-logo"' in jbody and "job-logo-initial" not in jbody.split('class="job-logo"')[1][:200], "annonsen visar arbetsgivarens logotyp")
    page.goto(f"{BASE}/admin/jobb/statistik")
    content = page.content()
    check("Statistik för jobbannonser" in content and "Förvaltningsrätten i Karlstad" in content, "jobbstatistiken visar arbetsgivare som inte är partners")
    jid = re.search(r'href="/ut/ansok/(\d+)"', jbody)
    page.goto(f"{BASE}/admin/jobb/{jid.group(1)}") if jid else None
    check(page.locator(".job-stats-card").count() == 1, "annonsens egen statistik visas på redigeringssidan")
    check(page.locator("[name=employer_pick] option:checked").inner_text() == "Förvaltningsrätten i Karlstad", "arbetsgivaren är vald när annonsen öppnas igen")
    st, _, _ = get("/admin/jobb/statistik.csv")
    check(st in (302, 303), "jobbstatistiken kräver inloggning")

    # ───────── Engagera dig ─────────
    print("Engagera dig")
    page.goto(f"{BASE}/admin/uppdrag/ny")
    page.fill("[name=title]", "Sexmästare")
    page.fill("[name=committee]", "Sexmästeriet")
    page.fill("[name=description]", "Planera sittningar och fester.")
    page.fill("[name=commitment]", "Några timmar i veckan")
    page.click("form.admin-form button[type=submit]")
    page.wait_for_url(re.compile(r"/admin/uppdrag\?klart="))
    pub = browser.new_page(viewport={"width": 390, "height": 844})
    pub.goto(f"{BASE}/engagera-dig")
    check(pub.locator(".position-card").count() == 1, "uppdraget visas på Engagera dig")
    pub.click(".position-card a")
    pub.wait_for_timeout(500)
    pub.fill("#falt-namn", "Anna Andersson")
    pub.fill("#falt-epost", "anna@example.com")
    pub.screenshot(path=str(OUT / "engagera-mobil.png"), full_page=True)
    time.sleep(3)  # tidstoken i formuläret
    pub.locator("main form button[type=submit]").last.click()
    pub.wait_for_url(re.compile(r"/engagera-dig/tack"))
    check(True, "intresseanmälan skickas")
    page.goto(f"{BASE}/admin/meddelanden")
    check("Engagera dig" in page.content(), "anmälan syns under Meddelanden")

    # ───────── Schemaläggning och kopiering ─────────
    print("Schemaläggning och kopiering")
    page.goto(f"{BASE}/admin/event/ny")
    page.fill("[name=title]", "Framtida sittning")
    page.fill("[name=starts_at]", "2030-03-01T18:00")
    page.fill("[name=publish_at]", "2030-01-01T08:00")
    page.click("form.admin-form button[type=submit]")
    page.wait_for_url(re.compile(r"klart=schemalagt"))
    check(page.locator(".pill-plan").count() >= 1, "listan visar ”Schemalagd”")
    status, body, _ = get("/kalender")
    check("Framtida sittning" not in body, "schemalagt event syns inte förrän tiden kommit")
    page.locator("tr:has-text('Framtida sittning') form[action$='/kopiera'] button").click()
    page.wait_for_url(re.compile(r"/admin/event/\d+\?klart=kopierat"))
    check("(kopia)" in page.locator("[name=title]").input_value(), "kopian öppnas för redigering")

    # ───────── Styrelseskifte ─────────
    print("Styrelseskifte")
    page.goto(f"{BASE}/admin/styrelseskifte")
    page.locator(".handover-check input").nth(0).check()
    page.locator(".handover-check input").nth(2).check()
    page.click("form.admin-form button[type=submit]")
    page.wait_for_url(re.compile(r"klart=sparat"))
    check("2 av 11 steg klara" in page.content(), "checklistan sparar framstegen")
    page.screenshot(path=str(OUT / "styrelseskifte.png"), full_page=True)

    # ───────── Kalenderprenumeration ─────────
    st, ics, hdr = get("/kalender.ics")
    check(st == 200 and ics.startswith("BEGIN:VCALENDAR") and "text/calendar" in hdr.get("content-type", ""), "kalenderflödet fungerar")
    check(all(len(line.encode()) <= 75 for line in ics.split("\r\n")), "raderna i kalenderflödet är högst 75 byte")

    noise = [e for e in errors if "favicon" not in e and "status of 422" not in e]  # 422 = avsiktligt valideringsfel
    check(not noise, f"inga JavaScript-fel i adminpanelen {noise[:3]}")
    browser.close()

done()
